name: example-environment
channels:
  - conda-forge
dependencies:
  - pyjnius
# try downgrade to get serving files working
  - jupyterlab==0.35.3
#  - nbconvert==5.4.1
  - notebook==5.7.5
#  - numpy
#  - psutil
#  - toolz
#  - matplotlib
#  - dill
#  - pandas
#  - partd
#  - bokeh
#  - dask
